=== hethport/tlh_dig_ui/annot.dtd
<!ELEMENT AOxml (AOHeader, body)>

  <!-- Header -->

  <!ELEMENT AOHeader (docID, meta)>

  <!ELEMENT docID (#PCDATA)>

  <!ELEMENT meta (creation-date, kor2, AOxml-creation, annotation)>

  <!ELEMENT creation-date EMPTY>
  <!ATTLIST creation-date date CDATA #REQUIRED>

  <!ELEMENT kor2 EMPTY>
  <!ATTLIST kor2 date CDATA #REQUIRED>

  <!ELEMENT AOxml-creation EMPTY>
  <!ATTLIST AOxml-creation date CDATA #REQUIRED>

  <!ELEMENT annotation (annot+)>

  <!ELEMENT annot EMPTY>
  <!ATTLIST annot
    date CDATA #REQUIRED
    editor CDATA #REQUIRED
    >

  <!-- Body -->
  <!ELEMENT body (AO:Manuscripts, div1)>

  <!ELEMENT AO:Manuscripts (AO:TxtPubl)>

  <!ELEMENT AO:TxtPubl (#PCDATA)>

  <!ELEMENT div1 (text)>
  <!ATTLIST div1 type CDATA #REQUIRED>

  <!ELEMENT text (p | parsep | parsep_dbl)+>

  <!ELEMENT parsep EMPTY>

  <!ELEMENT parsep_dbl EMPTY>

  <!ELEMENT p (s)>

  <!ELEMENT s ( gap | lb | w)+>


  <!ELEMENT gap EMPTY>
  <!ATTLIST gap
    c CDATA #REQUIRED
    t CDATA #IMPLIED
    >

  <!ELEMENT lb EMPTY>
  <!ATTLIST lb
    lg CDATA #REQUIRED
    lnr CDATA #REQUIRED
    txtid CDATA #REQUIRED
    >

  <!-- Words -->

  <!ELEMENT w (del_in | del_fin | ras_in | ras_fin | laes_in | laes_fin | d | sGr | aGr | num | space | corr | SP___AO_3a_MaterLect | SP___AO_3a_-KolonMark | note)+>
  <!ATTLIST w
    lg CDATA #IMPLIED
    mrp0sel CDATA #IMPLIED
    mrp1 CDATA #IMPLIED
    mrp2 CDATA #IMPLIED
    mrp3 CDATA #IMPLIED
    mrp4 CDATA #IMPLIED
    mrp5 CDATA #IMPLIED
    mrp6 CDATA #IMPLIED
    mrp7 CDATA #IMPLIED
    mrp8 CDATA #IMPLIED
    mrp9 CDATA #IMPLIED
    trans CDATA #IMPLIED
    >

  <!ELEMENT del_in EMPTY>
  <!ELEMENT del_fin EMPTY>

  <!ELEMENT laes_in EMPTY>
  <!ELEMENT laes_fin EMPTY>

  <!ELEMENT ras_in EMPTY>
  <!ELEMENT ras_fin EMPTY>

  <!-- Sumerogramm -->
  <!ELEMENT sGr (del_in | del_fin | ras_in | ras_fin | laes_in  | laes_fin | #PCDATA)+>

  <!-- Akadogramm -->
  <!ELEMENT aGr (del_in | del_fin | ras_in | ras_fin | laes_in  | laes_fin | #PCDATA)+>

  <!-- Determinativ -->
  <!ELEMENT d (del_in | del_fin | ras_in | ras_fin | laes_in  | laes_fin | #PCDATA)+>

  <!ELEMENT num (del_in | del_fin | ras_in | ras_fin | laes_in  | laes_fin | #PCDATA)+>

  <!ELEMENT SP___AO_3a_MaterLect (#PCDATA)>

  <!ELEMENT SP___AO_3a_-KolonMark (#PCDATA)>

  <!ELEMENT corr EMPTY>
  <!ATTLIST corr c CDATA #REQUIRED>

  <!ELEMENT space EMPTY>
  <!ATTLIST space c CDATA #REQUIRED>

  <!ELEMENT note EMPTY>
  <!ATTLIST note
    c CDATA #REQUIRED
    n CDATA #REQUIRED
    >

  <!-- Missing elements! -->
  <!ELEMENT AO:SIGN EMPTY>

=== hethport/tlh_dig_ui/KBo 4.9_short.xml
<?xml-stylesheet href="HPMxml.css" type="text/css"?>
<!DOCTYPE AOxml SYSTEM 'annot.dtd'>
<AOxml
  xmlns:AO="http://hethiter.net/ns/AO/1.0"
  xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
  xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
  xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"
  xml:space="preserve">
<AOHeader>
  <docID>KBo 4.9</docID>
  <meta>
    <creation-date date='2016-03-01T14:03:01.495000000'/>
    <kor2 date='2020-10-14T22:01:17'/>
    <AOxml-creation date='2020-10-14T22:01:17'/>
    <annotation>
      <annot editor='auto' date=''/>
      <annot editor='' date=''/>
  </annotation>
  </meta>
</AOHeader>
  <body>
    <AO:Manuscripts>
      <AO:TxtPubl>KBo 4.9</AO:TxtPubl>
    </AO:Manuscripts>
    <div1 type='transliteration'>
    <text xml:lang='XXXlang'>
      <p>
        <s xml:lang='XXXlang'>

          <lb txtid="KBo 4.9" lnr="Vs. I 1" lg="Hit"/>

          <w trans='LUGALuš' mrp0sel=' 1a '
             mrp1=' LUGAL @ König @
		{ a → FNL(u).NOM.SG.C}
		{ b → ACC.PL.C} @ 28.3.1.1 @ '
          ><sGr><del_in/>LUGA<del_fin/>L</sGr>-<laes_in/>uš<laes_fin/></w>

          <w trans='eša' mrp0sel='  '
             mrp1=' eš- @ sitzen @ 3SG.PRS.MP @ III.1.3 @ '
             mrp2=' eš=(i)- @ Kurtisane(?) @
		{ a → LUW.NOM/ACC.COLL}
		{ b → HITT.VOC.SG}
		{ c → HITT.ALL}
		{ d → HITT.STF} @ 30.1.1 @ MUNUS'
          >e-ša</w>

          <w trans='wakanna' mrp0sel=' 1 '
             mrp1=' wak= @ (ab)beißen @ INF @ II.1 @ '
          >wa-ga-an-n<del_in/>a</w>

          <w trans='ḫalzia' mrp0sel='  '
             mrp1=' ḫalz=i- @ Festung @
		{ a → D/L.SG}
		{ b → ALL} @ 2.1.1 @ '
             mrp2=' ḫalz=iya- @ rufen @ 2SG.IMP @ I.7 @ '
             mrp3=' ḫalzi=ya- @ rufen @ 3SG.PRS.MP @ III.5.1 @ '
          >ḫal-zi-ia<del_fin/></w>

          <lb txtid="KBo 4.9" lnr="Vs. I 2" lg="Hit"/>

          <w trans='Ú-UL' mrp0sel=' 1 '
             mrp1=' UL @ nicht @ NEG @  @ '
          ><aGr><laes_in/>Ú<laes_fin/>-UL</aGr></w>

          <w trans='kuitki' mrp0sel='  '
             mrp1=' kuiški @ irgendein @
		{ a → INDFany.NOM.SG.N}
		{ b → INDFany.ACC.SG.N} @ 24 @ '
          >ku-it-ki</w>

          <w trans='šipanti' mrp0sel='  '
             mrp1=' šipant= @ libieren @
		{ a → 3SG.PRS}
		{ b → 2SG.IMP} @ II.1.3 @ '
          >ši-pa-an-t<del_in/>i<del_fin/></w>

          <lb txtid="KBo 4.9" lnr="Vs. I 3" lg="Hit"/>

          <w trans='našta' mrp0sel=' 2a '
             mrp1=' n=ašta @  @ CONNn=OBPst @  @ '
             mrp2=' n=at=šta @  @
		{ a → CONNn=PPRO.3SG.N.NOM=OBPst}
		{ b → CONNn=PPRO.3SG.N.ACC=OBPst} @  @ '
             mrp3=' n=an=šta @  @ CONNn=PPRO.3SG.C.ACC=OBPst @  @ '
             mrp4=' n=aš=šta @  @
		{ a → CONNn=PPRO.3SG.C.NOM=OBPst}
		{ b → CONNn=PPRO.3PL.C.ACC=OBPst} @  @ '
          ><del_in/>n<del_fin/>a-aš-ta</w>

          <w trans='LUGALuš' mrp0sel='  '
             mrp1=' LUGAL @ König @
		{ a → FNL(u).NOM.SG.C}
		{ b → ACC.PL.C} @ 28.3.1.1 @ '
          ><sGr>LUGAL</sGr>-uš</w>

          <w trans='IŠ-TU É' mrp0sel=' 1   '
             mrp1=' É @ Haus @ ABL @ 28.16 @ '><aGr>IŠ-TU</aGr>
            <sGr>É</sGr></w>

          <w trans='ZA-BA₄-BA₄' mrp0sel='  '
             mrp1=' ZABABA @ Zababa @
		{ a → DN.NOM.SG.C(UNM)}
		{ b → DN.ACC.SG.C(UNM)}
		{ c → DN.GEN.SG(UNM)}
		{ d → DN.D/L.SG(UNM)}
		{ e → DN.ABL(UNM)}
		{ f → DN.INS(UNM)}
		{ g → DN.VOC.SG(UNM)} @  @ D'
          ><aGr>ZA-B<del_in/>A₄-BA₄<del_fin/></aGr></w>

          <lb txtid="KBo 4.9" lnr="Vs. I 4" lg="Hit"/>

          <w trans='para' mrp0sel='  '
             mrp1=' parā @ außerdem @  @ ADV @ '
             mrp2=' parā @ aus (zu) @  @ PREV @ '
             mrp3=' parā @ heraus aus @  @ POSP @ '
             mrp4=' par=a- @ Luft @
		{ a → VOC.SG}
		{ b → ALL}
		{ c → STF} @ 1.1 @ '
          >pa-ra-a</w>

          <w trans='wezi' mrp0sel=' 1 '
             mrp1=' wē-/uwa- @ kommen @ 3SG.PRS @ I.12 @ '
          >ú-ez-zi</w>
     </s>
      </p>
      <parsep/>
      <p>
        <s>
          <lb txtid="KBo 4.9" lnr="Vs. I 5" lg="Hit"/>

          <w trans='2' mrp0sel=' 1 '
             mrp1='  @ zwei @  @ QUANcar @ '
          ><num><laes_in/>2<laes_fin/></num></w>

          <w trans='DUMU.É.GAL' mrp0sel='  '
             mrp1=' DUMU.É.GAL @ Palastbediensteter @
		{ a → NOM.SG.C(UNM)}
		{ b → ACC.SG.C(UNM)}
		{ c → NOM.PL.C(UNM)}
		{ d → ACC.PL.C(UNM)}
		{ e → GEN.SG(UNM)}
		{ f → GEN.PL(UNM)}
		{ g → D/L.SG(UNM)}
		{ h → D/L.PL(UNM)}
		{ i → ALL(UNM)}
		{ j → ABL(UNM)}
		{ k → INS(UNM)}
		{ l → VOC.SG(UNM)}
		{ m → VOC.PL(UNM)} @ 28.2.1.1 @ '
          ><sGr>DUMU.É.GAL</sGr></w>

          <w trans='1' mrp0sel=' 1 '
             mrp1='  @ ein @  @ QUANcar @ '
          ><num>1</num></w>

          <w trans='ME-ŠE-DI' mrp0sel='  '
             mrp1=' MEŠĒDU @ Leibwächter @
		{ a → NOM.SG.C(UNM)}
		{ b → ACC.SG.C(UNM)}
		{ c → NOM.PL.C(UNM)}
		{ d → ACC.PL.C(UNM)}
		{ e → GEN.SG(UNM)}
		{ f → GEN.PL(UNM)}
		{ g → D/L.SG(UNM)}
		{ h → D/L.PL(UNM)}
		{ i → ALL(UNM)}
		{ j → ABL(UNM)}
		{ k → INS(UNM)}
		{ l → VOC.SG(UNM)}
		{ m → VOC.PL(UNM)} @  @ LÚ(.MEŠ)'
          ><d>LÚ</d>
            <aGr>ME-ŠE-DI</aGr></w>

          <w trans='peran' mrp0sel='  '
             mrp1=' peran @ vor @  @ ADV @ '
             mrp2=' peran @ vor @  @ POSP @ '
             mrp3=' peran @ vor @  @ PREV @ '
          >pé-<laes_in/>ra<laes_fin/>-an</w>

          <lb txtid="KBo 4.9" lnr="Vs. I 6" lg="Hit"/>

          <w trans='ḫuaianteš' mrp0sel='  '
             mrp1=' ḫuw=āye/a- @ laufen @
		{ a → PTCP.NOM.PL.C}
		{ b → PTCP.ACC.PL.C} @ I.7.5 @ '
          >ḫu-u-wa-ia-an-te-eš</w>

          <w trans='LUGALuš' mrp0sel='  '
             mrp1=' LUGAL @ König @
		{ a → FNL(u).NOM.SG.C}
		{ b → ACC.PL.C} @ 28.3.1.1 @ '
          ><sGr>LUGAL</sGr>-uš</w>

          <w trans='ḫalentuaš' mrp0sel='  '
             mrp1=' ḫalentuw=a- @ Palast @
		{ a → GEN.SG}
		{ b → GEN.PL}
		{ c → D/L.PL} @ 1.2 @ É'
             mrp2=' ḫalent=u- @ Palast @
		{ a → GEN.SG}
		{ b → GEN.PL}
		{ c → D/L.PL} @ 3.1.2 @ É'
          ><d>É</d>ḫa-le-en-tu-wa-aš</w>

          <lb txtid="KBo 4.9" lnr="Vs. I 7" lg="Hit"/>

          <w trans='paizi' mrp0sel=' 1 '
             mrp1=' pai-/pā- @ gehen @ 3SG.PRS @ I.11 @ '
          >pa-iz-zi</w>

          <w trans='ta' mrp0sel='  '
             mrp1=' ta @  @ CONNt @  @ '
             mrp2=' dā-/d- @ nehmen @ 2SG.IMP @ II.2 @ '
          >ta</w>

          <w trans='mân' mrp0sel=' 1 '
             mrp1=' mân @ wie @  @ POSP @ '
          >ma-a-an</w>

          <w trans='LUGALi' mrp0sel=' 1 '
             mrp1=' LUGAL @ König @ D/L.SG @ 28.3.1.1 @ '
          ><sGr>LUGAL</sGr>-i</w>

          <w trans='ZIanza' mrp0sel=' 1 '
             mrp1=' ZI @ Seele @ FNL(an).NOM.SG.C @ 28.9.1 @ '
          ><sGr>ZI</sGr>-an-za</w>

          <lb txtid="KBo 4.9" lnr="Vs. I 8" lg="Hit"/>

          <w trans='ta' mrp0sel='  '
             mrp1=' ta @  @ CONNt @  @ '
             mrp2=' dā-/d- @ nehmen @ 2SG.IMP @ II.2 @ '
          >ta</w>

          <w trans='araḫza' mrp0sel='  '
             mrp1=' araḫz=a- @ umliegend @
		{ a → ALL}
		{ b → VOC.SG}
		{ c → NOM.PL.N}
		{ d → ACC.PL.N}
		{ e → STF} @ 1.3 @ '
             mrp2=' araḫza @ (nach) draußen @  @ ADV @ '
          >a-ra-aḫ-za</w>

          <w trans='paizi' mrp0sel=' 1 '
             mrp1=' pai-/pā- @ gehen @ 3SG.PRS @ I.11 @ '
          >pa-iz-zi</w>

          <lb txtid="KBo 4.9" lnr="Vs. I 9" lg="Hit"/>

          <w trans='GIMan' mrp0sel=' 1 '
             mrp1=' GIM-an @ wie @ CNJ @  @ '
          ><sGr>GIM</sGr>-an</w>

          <w trans='LUGALi' mrp0sel=' 1 '
             mrp1=' LUGAL @ König @ D/L.SG @ 28.3.1.1 @ '
          ><sGr>LUGAL</sGr>-i</w>

          <w trans='ZIza' mrp0sel=' 1 '
             mrp1=' ZI @ Seele @ NOM.SG.C @ 28.9.1 @ '
          ><ras_in/><sGr>ZI</sGr>-za<ras_fin/></w>

          <w trans='nu' mrp0sel=' 1 '
             mrp1=' nu @  @ CONNn @  @ '
          >nu</w>

          <w trans='QA-TAM-MA' mrp0sel=' 1 '
             mrp1=' QĀTAMMA @ ebenso @ ADV @  @ '
          ><aGr>QA-TAM-MA</aGr></w>

          <lb txtid="KBo 4.9" lnr="Vs. I 10" lg="Hit"/>

          <w trans='iazi' mrp0sel='  '
             mrp1='  @ durchbohren @ 3SG.PRS @ I.7 @ '
             mrp2=' iye/a- @ machen @ 3SG.PRS @ I.7.1 @ '
          ><laes_in/>i<laes_fin/>-ia-zi</w>

          <w trans='Ú-UL' mrp0sel=' 1 '
             mrp1=' UL @ nicht @ NEG @  @ '
          ><aGr>Ú-UL</aGr></w>

          <w trans='kuitki' mrp0sel='  '
             mrp1=' kuiški @ irgendein @
		{ a → INDFany.NOM.SG.N}
		{ b → INDFany.ACC.SG.N} @ 24 @ '
          >ku-it-ki</w>

          <w trans='tukkari' mrp0sel=' 1 '
             mrp1=' dukk= @ gesehen werden @ 3SG.PRS.MP @ III.1 @ '
          >du-uk-ka₄-ri</w>
       </s>
      </p>
      <parsep/>

   </text>
  </div1>
  </body>
</AOxml>
